USE lcs

DROP TABLE Class
DROP TABLE Users
DROP TABLE Post
DROP TABLE Comment

CREATE TABLE Class(
	classID int NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	className varchar(255)
);

CREATE TABLE Users(
	userID int NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	googleID VARCHAR(255) NOT NULL,
	username VARCHAR(255) UNIQUE,
	fname VARCHAR(255),
	lname VARCHAR(255),
	profilePicture VARCHAR(255),
	classID INT,
	FOREIGN KEY (classID) REFERENCES Class (classID)
);

CREATE TABLE Post(
	postID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	title VARCHAR(255),
	content TEXT,
	published DATETIME,
	userID INT,
	FOREIGN KEY (userID) REFERENCES Users(userID)
);

CREATE TABLE Comment(
	commentID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	content TEXT,
	published DATETIME,
	userID INT,
	postID INT,
	FOREIGN KEY (userID) REFERENCES Users(userID),
	FOREIGN KEY (postID) REFERENCES Post(postID)
);

